package dev.saariselka.lcsgg.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Getter
@NoArgsConstructor
public class Challenges extends BaseInfo {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "challenges_id")
    private Long id;

    @Column(name = "12AssistStreakCount")
    private int assistStreakCount;
    private int abilityUses;
    private int acesBefore15Minutes;
    private int alliedJungleMonsterKills;
    private int baronTakedowns;
    private int blastConeOppositeOpponentCount;
    private int bountyGold;
    private int buffsStolen;
    private int completeSupportQuestInTime;
    private int controlWardsPlaced;
    private int damagePerMinute;
    private int damageTakenOnTeamPercentage;
    private int dancedWithRiftHerald;
    private int deathsByEnemyChamps;
    private int dodgeSkillShotsSmallWindow;
    private int doubleAces;
    private int dragonTakedowns;
    private int earlyLaningPhaseGoldExpAdvantage;
    private int effectiveHealAndShielding;
    private int elderDragonKillsWithOpposingSoul;
    private int elderDragonMultikills;
    private int enemyChampionImmobilizations;
    private int enemyJungleMonsterKills;
    private int epicMonsterKillsNearEnemyJungler;
    private int epicMonsterKillsWithin30SecondsOfSpawn;
    private int epicMonsterSteals;
    private int epicMonsterStolenWithoutSmite;
    private int flawlessAces;
    private int fullTeamTakedown;
    private int gameLength;
    private int getTakedownsInAllLanesEarlyJungleAsLaner;
    private int goldPerMinute;
    private int hadOpenNexus;
    private int immobilizeAndKillWithAlly;
    private int initialBuffCount;
    private int initialCrabCount;
    private int jungleCsBefore10Minutes;
    private int junglerTakedownsNearDamagedEpicMonster;
    private int kTurretsDestroyedBeforePlatesFall;
    private int kda;
    private int killAfterHiddenWithAlly;
    private int killParticipation;
    private int killedChampTookFullTeamDamageSurvived;
    private int killsNearEnemyTurret;
    private int killsOnOtherLanesEarlyJungleAsLaner;
    private int killsOnRecentlyHealedByAramPack;
    private int killsUnderOwnTurret;
    private int killsWithHelpFromEpicMonster;
    private int knockEnemyIntoTeamAndKill;
    private int landSkillShotsEarlyGame;
    private int laneMinionsFirst10Minutes;
    private int laningPhaseGoldExpAdvantage;
    private int legendaryCount;
    private int lostAnInhibitor;
    private int maxCsAdvantageOnLaneOpponent;
    private int maxKillDeficit;
    private int maxLevelLeadLaneOpponent;
    private int moreEnemyJungleThanOpponent;
    private int multiKillOneSpell;
    private int multiTurretRiftHeraldCount;
    private int multikills;
    private int multikillsAfterAggressiveFlash;
    private int mythicItemUsed;
    private int outerTurretExecutesBefore10Minutes;
    private int outnumberedKills;
    private int outnumberedNexusKill;
    private int perfectDragonSoulsTaken;
    private int perfectGame;
    private int pickKillWithAlly;
    private int playedChampSelectPosition;
    private int poroExplosions;
    private int quickCleanse;
    private int quickFirstTurret;
    private int quickSoloKills;
    private int riftHeraldTakedowns;
    private int saveAllyFromDeath;
    private int scuttleCrabKills;
    private int skillshotsDodged;
    private int skillshotsHit;
    private int snowballsHit;
    private int soloBaronKills;
    private int soloKills;
    private int stealthWardsPlaced;
    private int survivedSingleDigitHpCount;
    private int survivedThreeImmobilizesInFight;
    private int takedownOnFirstTurret;
    private int takedowns;
    private int takedownsAfterGainingLevelAdvantage;
    private int takedownsBeforeJungleMinionSpawn;
    private int takedownsFirstXMinutes;
    private int takedownsInAlcove;
    private int takedownsInEnemyFountain;
    private int teamBaronKills;
    private int teamDamagePercentage;
    private int teamElderDragonKills;
    private int teamRiftHeraldKills;
    private int threeWardsOneSweeperCount;
    private int tookLargeDamageSurvived;
    private int turretPlatesTaken;
    private int turretTakedowns;
    private int turretsTakenWithRiftHerald;
    private int twentyMinionsIn3SecondsCount;
    private int unseenRecalls;
    private int visionScoreAdvantageLaneOpponent;
    private int visionScorePerMinute;
    private int wardTakedowns;
    private int wardTakedownsBefore20M;
    private int wardsGuarded;

    // 연관관계 매핑
    @OneToOne(cascade = CascadeType.PERSIST)
    @JoinColumn(name = "participant_id")
    private Participant participant;

    // 연관관계 설정
    public void setParticipant(Participant participant) { this.participant = participant; }

    public Challenges(int assistStreakCount, int abilityUses, int acesBefore15Minutes, int alliedJungleMonsterKills, int baronTakedowns, int blastConeOppositeOpponentCount, int bountyGold, int buffsStolen, int completeSupportQuestInTime, int controlWardsPlaced, int damagePerMinute, int damageTakenOnTeamPercentage, int dancedWithRiftHerald, int deathsByEnemyChamps, int dodgeSkillShotsSmallWindow, int doubleAces, int dragonTakedowns, int earlyLaningPhaseGoldExpAdvantage, int effectiveHealAndShielding, int elderDragonKillsWithOpposingSoul, int elderDragonMultikills, int enemyChampionImmobilizations, int enemyJungleMonsterKills, int epicMonsterKillsNearEnemyJungler, int epicMonsterKillsWithin30SecondsOfSpawn, int epicMonsterSteals, int epicMonsterStolenWithoutSmite, int flawlessAces, int fullTeamTakedown, int gameLength, int getTakedownsInAllLanesEarlyJungleAsLaner, int goldPerMinute, int hadOpenNexus, int immobilizeAndKillWithAlly, int initialBuffCount, int initialCrabCount, int jungleCsBefore10Minutes, int junglerTakedownsNearDamagedEpicMonster, int kTurretsDestroyedBeforePlatesFall, int kda, int killAfterHiddenWithAlly, int killParticipation, int killedChampTookFullTeamDamageSurvived, int killsNearEnemyTurret, int killsOnOtherLanesEarlyJungleAsLaner, int killsOnRecentlyHealedByAramPack, int killsUnderOwnTurret, int killsWithHelpFromEpicMonster, int knockEnemyIntoTeamAndKill, int landSkillShotsEarlyGame, int laneMinionsFirst10Minutes, int laningPhaseGoldExpAdvantage, int legendaryCount, int lostAnInhibitor, int maxCsAdvantageOnLaneOpponent, int maxKillDeficit, int maxLevelLeadLaneOpponent, int moreEnemyJungleThanOpponent, int multiKillOneSpell, int multiTurretRiftHeraldCount, int multikills, int multikillsAfterAggressiveFlash, int mythicItemUsed, int outerTurretExecutesBefore10Minutes, int outnumberedKills, int outnumberedNexusKill, int perfectDragonSoulsTaken, int perfectGame, int pickKillWithAlly, int playedChampSelectPosition, int poroExplosions, int quickCleanse, int quickFirstTurret, int quickSoloKills, int riftHeraldTakedowns, int saveAllyFromDeath, int scuttleCrabKills, int skillshotsDodged, int skillshotsHit, int snowballsHit, int soloBaronKills, int soloKills, int stealthWardsPlaced, int survivedSingleDigitHpCount, int survivedThreeImmobilizesInFight, int takedownOnFirstTurret, int takedowns, int takedownsAfterGainingLevelAdvantage, int takedownsBeforeJungleMinionSpawn, int takedownsFirstXMinutes, int takedownsInAlcove, int takedownsInEnemyFountain, int teamBaronKills, int teamDamagePercentage, int teamElderDragonKills, int teamRiftHeraldKills, int threeWardsOneSweeperCount, int tookLargeDamageSurvived, int turretPlatesTaken, int turretTakedowns, int turretsTakenWithRiftHerald, int twentyMinionsIn3SecondsCount, int unseenRecalls, int visionScoreAdvantageLaneOpponent, int visionScorePerMinute, int wardTakedowns, int wardTakedownsBefore20M, int wardsGuarded, Participant participant) {
        this.assistStreakCount = assistStreakCount;
        this.abilityUses = abilityUses;
        this.acesBefore15Minutes = acesBefore15Minutes;
        this.alliedJungleMonsterKills = alliedJungleMonsterKills;
        this.baronTakedowns = baronTakedowns;
        this.blastConeOppositeOpponentCount = blastConeOppositeOpponentCount;
        this.bountyGold = bountyGold;
        this.buffsStolen = buffsStolen;
        this.completeSupportQuestInTime = completeSupportQuestInTime;
        this.controlWardsPlaced = controlWardsPlaced;
        this.damagePerMinute = damagePerMinute;
        this.damageTakenOnTeamPercentage = damageTakenOnTeamPercentage;
        this.dancedWithRiftHerald = dancedWithRiftHerald;
        this.deathsByEnemyChamps = deathsByEnemyChamps;
        this.dodgeSkillShotsSmallWindow = dodgeSkillShotsSmallWindow;
        this.doubleAces = doubleAces;
        this.dragonTakedowns = dragonTakedowns;
        this.earlyLaningPhaseGoldExpAdvantage = earlyLaningPhaseGoldExpAdvantage;
        this.effectiveHealAndShielding = effectiveHealAndShielding;
        this.elderDragonKillsWithOpposingSoul = elderDragonKillsWithOpposingSoul;
        this.elderDragonMultikills = elderDragonMultikills;
        this.enemyChampionImmobilizations = enemyChampionImmobilizations;
        this.enemyJungleMonsterKills = enemyJungleMonsterKills;
        this.epicMonsterKillsNearEnemyJungler = epicMonsterKillsNearEnemyJungler;
        this.epicMonsterKillsWithin30SecondsOfSpawn = epicMonsterKillsWithin30SecondsOfSpawn;
        this.epicMonsterSteals = epicMonsterSteals;
        this.epicMonsterStolenWithoutSmite = epicMonsterStolenWithoutSmite;
        this.flawlessAces = flawlessAces;
        this.fullTeamTakedown = fullTeamTakedown;
        this.gameLength = gameLength;
        this.getTakedownsInAllLanesEarlyJungleAsLaner = getTakedownsInAllLanesEarlyJungleAsLaner;
        this.goldPerMinute = goldPerMinute;
        this.hadOpenNexus = hadOpenNexus;
        this.immobilizeAndKillWithAlly = immobilizeAndKillWithAlly;
        this.initialBuffCount = initialBuffCount;
        this.initialCrabCount = initialCrabCount;
        this.jungleCsBefore10Minutes = jungleCsBefore10Minutes;
        this.junglerTakedownsNearDamagedEpicMonster = junglerTakedownsNearDamagedEpicMonster;
        this.kTurretsDestroyedBeforePlatesFall = kTurretsDestroyedBeforePlatesFall;
        this.kda = kda;
        this.killAfterHiddenWithAlly = killAfterHiddenWithAlly;
        this.killParticipation = killParticipation;
        this.killedChampTookFullTeamDamageSurvived = killedChampTookFullTeamDamageSurvived;
        this.killsNearEnemyTurret = killsNearEnemyTurret;
        this.killsOnOtherLanesEarlyJungleAsLaner = killsOnOtherLanesEarlyJungleAsLaner;
        this.killsOnRecentlyHealedByAramPack = killsOnRecentlyHealedByAramPack;
        this.killsUnderOwnTurret = killsUnderOwnTurret;
        this.killsWithHelpFromEpicMonster = killsWithHelpFromEpicMonster;
        this.knockEnemyIntoTeamAndKill = knockEnemyIntoTeamAndKill;
        this.landSkillShotsEarlyGame = landSkillShotsEarlyGame;
        this.laneMinionsFirst10Minutes = laneMinionsFirst10Minutes;
        this.laningPhaseGoldExpAdvantage = laningPhaseGoldExpAdvantage;
        this.legendaryCount = legendaryCount;
        this.lostAnInhibitor = lostAnInhibitor;
        this.maxCsAdvantageOnLaneOpponent = maxCsAdvantageOnLaneOpponent;
        this.maxKillDeficit = maxKillDeficit;
        this.maxLevelLeadLaneOpponent = maxLevelLeadLaneOpponent;
        this.moreEnemyJungleThanOpponent = moreEnemyJungleThanOpponent;
        this.multiKillOneSpell = multiKillOneSpell;
        this.multiTurretRiftHeraldCount = multiTurretRiftHeraldCount;
        this.multikills = multikills;
        this.multikillsAfterAggressiveFlash = multikillsAfterAggressiveFlash;
        this.mythicItemUsed = mythicItemUsed;
        this.outerTurretExecutesBefore10Minutes = outerTurretExecutesBefore10Minutes;
        this.outnumberedKills = outnumberedKills;
        this.outnumberedNexusKill = outnumberedNexusKill;
        this.perfectDragonSoulsTaken = perfectDragonSoulsTaken;
        this.perfectGame = perfectGame;
        this.pickKillWithAlly = pickKillWithAlly;
        this.playedChampSelectPosition = playedChampSelectPosition;
        this.poroExplosions = poroExplosions;
        this.quickCleanse = quickCleanse;
        this.quickFirstTurret = quickFirstTurret;
        this.quickSoloKills = quickSoloKills;
        this.riftHeraldTakedowns = riftHeraldTakedowns;
        this.saveAllyFromDeath = saveAllyFromDeath;
        this.scuttleCrabKills = scuttleCrabKills;
        this.skillshotsDodged = skillshotsDodged;
        this.skillshotsHit = skillshotsHit;
        this.snowballsHit = snowballsHit;
        this.soloBaronKills = soloBaronKills;
        this.soloKills = soloKills;
        this.stealthWardsPlaced = stealthWardsPlaced;
        this.survivedSingleDigitHpCount = survivedSingleDigitHpCount;
        this.survivedThreeImmobilizesInFight = survivedThreeImmobilizesInFight;
        this.takedownOnFirstTurret = takedownOnFirstTurret;
        this.takedowns = takedowns;
        this.takedownsAfterGainingLevelAdvantage = takedownsAfterGainingLevelAdvantage;
        this.takedownsBeforeJungleMinionSpawn = takedownsBeforeJungleMinionSpawn;
        this.takedownsFirstXMinutes = takedownsFirstXMinutes;
        this.takedownsInAlcove = takedownsInAlcove;
        this.takedownsInEnemyFountain = takedownsInEnemyFountain;
        this.teamBaronKills = teamBaronKills;
        this.teamDamagePercentage = teamDamagePercentage;
        this.teamElderDragonKills = teamElderDragonKills;
        this.teamRiftHeraldKills = teamRiftHeraldKills;
        this.threeWardsOneSweeperCount = threeWardsOneSweeperCount;
        this.tookLargeDamageSurvived = tookLargeDamageSurvived;
        this.turretPlatesTaken = turretPlatesTaken;
        this.turretTakedowns = turretTakedowns;
        this.turretsTakenWithRiftHerald = turretsTakenWithRiftHerald;
        this.twentyMinionsIn3SecondsCount = twentyMinionsIn3SecondsCount;
        this.unseenRecalls = unseenRecalls;
        this.visionScoreAdvantageLaneOpponent = visionScoreAdvantageLaneOpponent;
        this.visionScorePerMinute = visionScorePerMinute;
        this.wardTakedowns = wardTakedowns;
        this.wardTakedownsBefore20M = wardTakedownsBefore20M;
        this.wardsGuarded = wardsGuarded;
        this.participant = participant;

        setParticipant(participant);
    }
}
