spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.caybrpuf0ihh.ap-northeast-2.rds.amazonaws.com:3306/sys?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: admin2022!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.SQL: debug
