package dev.saariselka.inlol.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.sql.Timestamp;

@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter

public class MatchParticipantDto {
    private String puuid;
    private String dataVersion;
    private String matchId;
    private String participantId;

    private String assists;
    private String baronKills;
    private String bountyLevel;
    private String champExperience;
    private String champLevel;
    private String championId;
    private String championName;
    private String championNameKR;
    private String championImg;
    private String championTransform;
    private String consumablesPurchased;
    private String damageDealtToBuildings;
    private String damageDealtToObjectives;
    private String damageDealtToTurrets;
    private String damageSelfMitigated;
    private String deaths;
    private String detectorWardsPlaced;
    private String doubleKills;
    private String dragonKills;
    private String firstBloodAssist;
    private String firstBloodKill;
    private String firstTowerAssist;
    private String firstTowerKill;
    private String gameEndedInEarlySurrender;
    private String gameEndedInSurrender;
    private String goldEarned;
    private String goldSpent;
    private String individualPosition;
    private String inhibitorKills;
    private String inhibitorTakedowns;
    private String inhibitorsLost;
    private String item0;
    private String item1;
    private String item2;
    private String item3;
    private String item4;
    private String item5;
    private String item6;
    private String itemsPurchased;
    private String killingSprees;
    private String kills;
    private String lane;
    private String largestCriticalStrike;
    private String largestKillingSpree;
    private String largestMultiKill;
    private String longestTimeSpentLiving;
    private String magicDamageDealt;
    private String magicDamageDealtToChampions;
    private String magicDamageTaken;
    private String neutralMinionsKilled;
    private String nexusKills;
    private String nexusTakedowns;
    private String nexusLost;
    private String objectivesStolen;
    private String objectivesStolenAssists;
    private String pentaKills;
    private String physicalDamageDealt;
    private String physicalDamageDealtToChampions;
    private String physicalDamageTaken;
    private String profileIcon;
    private String quadraKills;
    private String riotIdName;
    private String riotIdTagline;
    private String role;
    private String sightWardsBoughtInGame;
    private String spell1Casts;
    private String spell2Casts;
    private String spell3Casts;
    private String spell4Casts;
    private String summoner1Casts;
    private String summoner1Id;
    private String summoner2Casts;
    private String summoner2Id;
    private String summonerId;
    private String summonerLevel;
    private String summonerName;
    private String teamEarlySurrendered;
    private String teamId;
    private String teamPosition;
    private String timeCCingOthers;
    private String timePlayed;
    private String totalDamageDealt;
    private String totalDamageDealtToChampions;
    private String totalDamageShieldedOnTeammates;
    private String totalDamageTaken;
    private String totalHeal;
    private String totalHealsOnTeammates;
    private String totalMinionsKilled;
    private String totalTimeCCDealt;
    private String totalTimeSpentDead;
    private String totalUnitsHealed;
    private String tripleKills;
    private String trueDamageDealt;
    private String trueDamageDealtToChampions;
    private String trueDamageTaken;
    private String turretKills;
    private String turretTakedowns;
    private String turretsLost;
    private String unrealKills;
    private String visionScore;
    private String visionWardsBoughtInGame;
    private String wardsKilled;
    private String wardsPlaced;
    private String win;
    private Timestamp rrt;

    private MatchPerksDto perks;
    private String kda;
    private String minionsKilledPerMin;
    private String killRatio;
    private String multiKills;

    public MatchParticipantDto(String puuid
                               , String dataVersion
                               , String matchId
                               , int participantId
                               , int assists
                               , int baronKills
                               , int bountyLevel
                               , int champExperience
                               , int champLevel
                               , int championId
                               , String championName
                               , String championNameKR
                               , String championImg
                               , int championTransform
                               , int consumablesPurchased
                               , int damageDealtToBuildings
                               , int damageDealtToObjectives
                               , int damageDealtToTurrets
                               , int damageSelfMitigated
                               , int deaths
                               , int detectorWardsPlaced
                               , int doubleKills
                               , int dragonKills
                               , boolean firstBloodAssist
                               , boolean firstBloodKill
                               , boolean firstTowerAssist
                               , boolean firstTowerKill
                               , boolean gameEndedInEarlySurrender
                               , boolean gameEndedInSurrender
                               , int goldEarned
                               , int goldSpent
                               , String individualPosition
                               , int inhibitorKills
                               , int inhibitorTakedowns
                               , int inhibitorsLost
                               , int item0
                               , int item1
                               , int item2
                               , int item3
                               , int item4
                               , int item5
                               , int item6
                               , int itemsPurchased
                               , int killingSprees
                               , int kills
                               , String lane
                               , int largestCriticalStrike
                               , int largestKillingSpree
                               , int largestMultiKill
                               , int longestTimeSpentLiving
                               , int magicDamageDealt
                               , int magicDamageDealtToChampions
                               , int magicDamageTaken
                               , int neutralMinionsKilled
                               , int nexusKills
                               , int nexusTakedowns
                               , int nexusLost
                               , int objectivesStolen
                               , int objectivesStolenAssists
                               , int pentaKills
                               , int physicalDamageDealt
                               , int physicalDamageDealtToChampions
                               , int physicalDamageTaken
                               , int profileIcon
                               , int quadraKills
                               , String riotIdName
                               , String riotIdTagline
                               , String role
                               , int sightWardsBoughtInGame
                               , int spell1Casts
                               , int spell2Casts
                               , int spell3Casts
                               , int spell4Casts
                               , int summoner1Casts
                               , String summoner1Id
                               , int summoner2Casts
                               , String summoner2Id
                               , String summonerId
                               , int summonerLevel
                               , String summonerName
                               , boolean teamEarlySurrendered
                               , int teamId
                               , String teamPosition
                               , int timeCCingOthers
                               , int timePlayed
                               , int totalDamageDealt
                               , int totalDamageDealtToChampions
                               , int totalDamageShieldedOnTeammates
                               , int totalDamageTaken
                               , int totalHeal
                               , int totalHealsOnTeammates
                               , int totalMinionsKilled
                               , int totalTimeCCDealt
                               , int totalTimeSpentDead
                               , int totalUnitsHealed
                               , int tripleKills
                               , int trueDamageDealt
                               , int trueDamageDealtToChampions
                               , int trueDamageTaken
                               , int turretKills
                               , int turretTakedowns
                               , int turretsLost
                               , int unrealKills
                               , int visionScore
                               , int visionWardsBoughtInGame
                               , int wardsKilled
                               , int wardsPlaced
                               , boolean win
                               , Timestamp rrt) {
        this.puuid = puuid;
        this.dataVersion = dataVersion;
        this.matchId = matchId;
        this.participantId = String.valueOf(participantId);
        this.assists = String.valueOf(assists);
        this.baronKills = String.valueOf(baronKills);
        this.bountyLevel = String.valueOf(bountyLevel);
        this.champExperience = String.valueOf(champExperience);
        this.champLevel = String.valueOf(champLevel);
        this.championId = String.valueOf(championId);
        this.championName = championName;
        this.championNameKR = championNameKR;
        this.championImg = championImg;
        this.championTransform = String.valueOf(championTransform);
        this.consumablesPurchased = String.valueOf(consumablesPurchased);
        this.damageDealtToBuildings = String.valueOf(damageDealtToBuildings);
        this.damageDealtToObjectives = String.valueOf(damageDealtToObjectives);
        this.damageDealtToTurrets = String.valueOf(damageDealtToTurrets);
        this.damageSelfMitigated = String.valueOf(damageSelfMitigated);
        this.deaths = String.valueOf(deaths);
        this.detectorWardsPlaced = String.valueOf(detectorWardsPlaced);
        this.doubleKills = String.valueOf(doubleKills);
        this.dragonKills = String.valueOf(dragonKills);
        this.firstBloodAssist = String.valueOf(firstBloodAssist);
        this.firstBloodKill = String.valueOf(firstBloodKill);
        this.firstTowerAssist = String.valueOf(firstTowerAssist);
        this.firstTowerKill = String.valueOf(firstTowerKill);
        this.gameEndedInEarlySurrender = String.valueOf(gameEndedInEarlySurrender);
        this.gameEndedInSurrender = String.valueOf(gameEndedInSurrender);
        this.goldEarned = String.valueOf(goldEarned);
        this.goldSpent = String.valueOf(goldSpent);
        this.individualPosition =individualPosition;
        this.inhibitorKills = String.valueOf(inhibitorKills);
        this.inhibitorTakedowns = String.valueOf(inhibitorTakedowns);
        this.inhibitorsLost = String.valueOf(inhibitorsLost);
        this.item0 = String.valueOf(item0);
        this.item1 = String.valueOf(item1);
        this.item2 = String.valueOf(item2);
        this.item3 = String.valueOf(item3);
        this.item4 = String.valueOf(item4);
        this.item5 = String.valueOf(item5);
        this.item6 = String.valueOf(item6);
        this.itemsPurchased = String.valueOf(itemsPurchased);
        this.killingSprees = String.valueOf(killingSprees);
        this.kills = String.valueOf(kills);
        this.lane = lane;
        this.largestCriticalStrike = String.valueOf(largestCriticalStrike);
        this.largestKillingSpree = String.valueOf(largestKillingSpree);
        this.largestMultiKill = String.valueOf(largestMultiKill);
        this.longestTimeSpentLiving = String.valueOf(longestTimeSpentLiving);
        this.magicDamageDealt = String.valueOf(magicDamageDealt);
        this.magicDamageDealtToChampions = String.valueOf(magicDamageDealtToChampions);
        this.magicDamageTaken = String.valueOf(magicDamageTaken);
        this.neutralMinionsKilled = String.valueOf(neutralMinionsKilled);
        this.nexusKills = String.valueOf(nexusKills);
        this.nexusLost = String.valueOf(nexusLost);
        this.nexusTakedowns = String.valueOf(nexusTakedowns);
        this.objectivesStolen = String.valueOf(objectivesStolen);
        this.objectivesStolenAssists = String.valueOf(objectivesStolenAssists);
        this.pentaKills = String.valueOf(pentaKills);
        this.physicalDamageDealt = String.valueOf(physicalDamageDealt);
        this.physicalDamageDealtToChampions = String.valueOf(physicalDamageDealtToChampions);
        this.physicalDamageTaken = String.valueOf(physicalDamageTaken);
        this.profileIcon = String.valueOf(profileIcon);
        this.quadraKills = String.valueOf(quadraKills);
        this.riotIdName = riotIdName;
        this.riotIdTagline = riotIdTagline;
        this.role = role;
        this.sightWardsBoughtInGame = String.valueOf(sightWardsBoughtInGame);
        this.spell1Casts = String.valueOf(spell1Casts);
        this.spell2Casts = String.valueOf(spell2Casts);
        this.spell3Casts = String.valueOf(spell3Casts);
        this.spell4Casts = String.valueOf(spell4Casts);
        this.summoner1Casts = String.valueOf(summoner1Casts);
        this.summoner1Id = String.valueOf(summoner1Id);
        this.summoner2Casts = String.valueOf(summoner2Casts);
        this.summoner2Id = String.valueOf(summoner2Id);
        this.summonerId = summonerId;
        this.summonerLevel = String.valueOf(summonerLevel);
        if(puuid.equals("BOT")) {
            this.summonerName = "(봇)";
        } else {
            this.summonerName = summonerName;
        }
        this.teamEarlySurrendered = String.valueOf(teamEarlySurrendered);
        this.teamId = String.valueOf(teamId);
        this.teamPosition =teamPosition;
        this.timeCCingOthers = String.valueOf(timeCCingOthers);
        this.timePlayed = String.valueOf(timePlayed);
        this.totalDamageDealt = String.valueOf(totalDamageDealt);
        this.totalDamageDealtToChampions = String.valueOf(totalDamageDealtToChampions);
        this.totalDamageShieldedOnTeammates = String.valueOf(totalDamageShieldedOnTeammates);
        this.totalDamageTaken = String.valueOf(totalDamageTaken);
        this.totalHeal = String.valueOf(totalHeal);
        this.totalHealsOnTeammates = String.valueOf(totalHealsOnTeammates);
        this.totalMinionsKilled = String.valueOf(totalMinionsKilled);
        this.totalTimeCCDealt = String.valueOf(totalTimeCCDealt);
        this.totalTimeSpentDead = String.valueOf(totalTimeSpentDead);
        this.totalUnitsHealed = String.valueOf(totalUnitsHealed);
        this.tripleKills = String.valueOf(tripleKills);
        this.trueDamageDealt = String.valueOf(trueDamageDealt);
        this.trueDamageDealtToChampions = String.valueOf(trueDamageDealtToChampions);
        this.trueDamageTaken = String.valueOf(trueDamageTaken);
        this.turretKills = String.valueOf(turretKills);
        this.turretTakedowns = String.valueOf(turretTakedowns);
        this.turretsLost = String.valueOf(turretsLost);
        this.unrealKills = String.valueOf(unrealKills);
        this.visionScore = String.valueOf(visionScore);
        this.visionWardsBoughtInGame = String.valueOf(visionWardsBoughtInGame);
        this.wardsKilled = String.valueOf(wardsKilled);
        this.wardsPlaced = String.valueOf(wardsPlaced);
        this.win = String.valueOf(win);
        this.rrt = rrt;
    }

    public MatchParticipantDto(String puuid, String dataVersion, String matchId, String participantId) {
        this.puuid = puuid;
        this.dataVersion = dataVersion;
        this.matchId = matchId;
        this.participantId = participantId;
    }
}
