package dev.saariselka.inlol.dto;

import dev.saariselka.inlol.entity.MatchParticipantEntity;

public class ParticipantDto_Assembly {

    public ParticipantDto getParticipantDtoByEntity(MatchParticipantEntity matchParticipantEntity) {
        ParticipantDto participantDto = new ParticipantDto();

        participantDto.setPuuid(matchParticipantEntity.getMatchParticipantId().getPuuid());
        participantDto.setDataVersion(matchParticipantEntity.getMatchParticipantId().getDataVersion());
        participantDto.setMatchId(matchParticipantEntity.getMatchParticipantId().getMatchId());
        participantDto.setAssists(String.valueOf(matchParticipantEntity.getAssists()));
        participantDto.setBaronKills(String.valueOf(matchParticipantEntity.getBaronKills()));
        participantDto.setBountyLevel(String.valueOf(matchParticipantEntity.getBountyLevel()));
        participantDto.setChampExperience(String.valueOf(matchParticipantEntity.getChampExperience()));
        participantDto.setChampLevel(String.valueOf(matchParticipantEntity.getChampLevel()));
        participantDto.setChampionId(String.valueOf(matchParticipantEntity.getChampionName()));
        participantDto.setChampionNameENG(matchParticipantEntity.getChampionName());
        participantDto.setChampionTransform(String.valueOf(matchParticipantEntity.getChampionTransform()));
        participantDto.setConsumablesPurchased(String.valueOf(matchParticipantEntity.getConsumablesPurchased()));
        participantDto.setDamageDealtToBuildings(String.valueOf(matchParticipantEntity.getDamageDealtToBuildings()));
        participantDto.setDamageDealtToObjectives(String.valueOf(matchParticipantEntity.getDamageDealtToObjectives()));
        participantDto.setDamageDealtToTurrets(String.valueOf(matchParticipantEntity.getDamageDealtToTurrets()));
        participantDto.setDamageSelfMitigated(String.valueOf(matchParticipantEntity.getDamageSelfMitigated()));
        participantDto.setDeaths(String.valueOf(matchParticipantEntity.getDeaths()));
        participantDto.setDetectorWardsPlaced(String.valueOf(matchParticipantEntity.getDetectorWardsPlaced()));
        participantDto.setDoubleKills(String.valueOf(matchParticipantEntity.getDoubleKills()));
        participantDto.setDragonKills(String.valueOf(matchParticipantEntity.getDragonKills()));
        participantDto.setFirstBloodAssist(String.valueOf(matchParticipantEntity.isFirstBloodAssist()));
        participantDto.setFirstBloodKill(String.valueOf(matchParticipantEntity.isFirstBloodKill()));
        participantDto.setFirstTowerAssist(String.valueOf(matchParticipantEntity.isFirstTowerAssist()));
        participantDto.setFirstTowerKill(String.valueOf(matchParticipantEntity.isFirstTowerKill()));
        participantDto.setGameEndedInEarlySurrender(String.valueOf(matchParticipantEntity.isGameEndedInEarlySurrender()));
        participantDto.setGameEndedInSurrender(String.valueOf(matchParticipantEntity.isGameEndedInSurrender()));
        participantDto.setGoldEarned(String.valueOf(matchParticipantEntity.getGoldEarned()));
        participantDto.setGoldSpent(String.valueOf(matchParticipantEntity.getGoldSpent()));
        participantDto.setIndividualPosition(matchParticipantEntity.getIndividualPosition());
        participantDto.setInhibitorKills(String.valueOf(matchParticipantEntity.getInhibitorKills()));
        participantDto.setInhibitorTakedowns(String.valueOf(matchParticipantEntity.getInhibitorTakedowns()));
        participantDto.setInhibitorsLost(String.valueOf(matchParticipantEntity.getInhibitorsLost()));
        participantDto.setItem0(String.valueOf(matchParticipantEntity.getItem0()));
        participantDto.setItem1(String.valueOf(matchParticipantEntity.getItem1()));
        participantDto.setItem2(String.valueOf(matchParticipantEntity.getItem2()));
        participantDto.setItem3(String.valueOf(matchParticipantEntity.getItem3()));
        participantDto.setItem4(String.valueOf(matchParticipantEntity.getItem4()));
        participantDto.setItem5(String.valueOf(matchParticipantEntity.getItem5()));
        participantDto.setItem6(String.valueOf(matchParticipantEntity.getItem6()));
        participantDto.setItemsPurchased(String.valueOf(matchParticipantEntity.getItemsPurchased()));
        participantDto.setKillingSprees(String.valueOf(matchParticipantEntity.getKillingSprees()));
        participantDto.setKills(String.valueOf(matchParticipantEntity.getKills()));
        participantDto.setLane(matchParticipantEntity.getLane());
        participantDto.setLargestCriticalStrike(String.valueOf(matchParticipantEntity.getLargestCriticalStrike()));
        participantDto.setLargestKillingSpree(String.valueOf(matchParticipantEntity.getLargestKillingSpree()));
        participantDto.setLargestMultiKill(String.valueOf(matchParticipantEntity.getLargestMultiKill()));
        participantDto.setLongestTimeSpentLiving(String.valueOf(matchParticipantEntity.getLongestTimeSpentLiving()));
        participantDto.setMagicDamageDealt(String.valueOf(matchParticipantEntity.getMagicDamageDealt()));
        participantDto.setMagicDamageDealtToChampions(String.valueOf(matchParticipantEntity.getMagicDamageDealtToChampions()));
        participantDto.setMagicDamageTaken(String.valueOf(matchParticipantEntity.getMagicDamageTaken()));
        participantDto.setNeutralMinionsKilled(String.valueOf(matchParticipantEntity.getNeutralMinionsKilled()));
        participantDto.setNexusKills(String.valueOf(matchParticipantEntity.getNexusKills()));
        participantDto.setNexusLost(String.valueOf(matchParticipantEntity.getNexusLost()));
        participantDto.setNexusTakedowns(String.valueOf(matchParticipantEntity.getNexusTakedowns()));
        participantDto.setObjectivesStolen(String.valueOf(matchParticipantEntity.getObjectivesStolen()));
        participantDto.setObjectivesStolenAssists(String.valueOf(matchParticipantEntity.getObjectivesStolenAssists()));
        participantDto.setParticipantId(String.valueOf(matchParticipantEntity.getParticipantId()));
        participantDto.setPentaKills(String.valueOf(matchParticipantEntity.getPentaKills()));
        participantDto.setPhysicalDamageDealt(String.valueOf(matchParticipantEntity.getPhysicalDamageDealt()));
        participantDto.setPhysicalDamageDealtToChampions(String.valueOf(matchParticipantEntity.getPhysicalDamageDealtToChampions()));
        participantDto.setPhysicalDamageTaken(String.valueOf(matchParticipantEntity.getPhysicalDamageTaken()));
        participantDto.setProfileIcon(String.valueOf(matchParticipantEntity.getProfileIcon()));
        participantDto.setQuadraKills(String.valueOf(matchParticipantEntity.getQuadraKills()));
        participantDto.setRiotIdName(matchParticipantEntity.getRiotIdName());
        participantDto.setRiotIdTagline(matchParticipantEntity.getRiotIdTagline());
        participantDto.setRole(matchParticipantEntity.getRole());
        participantDto.setSightWardsBoughtInGame(String.valueOf(matchParticipantEntity.getSightWardsBoughtInGame()));
        participantDto.setSpell1Casts(String.valueOf(matchParticipantEntity.getSpell1Casts()));
        participantDto.setSpell2Casts(String.valueOf(matchParticipantEntity.getSpell2Casts()));
        participantDto.setSpell3Casts(String.valueOf(matchParticipantEntity.getSpell3Casts()));
        participantDto.setSpell4Casts(String.valueOf(matchParticipantEntity.getSpell4Casts()));
        participantDto.setSummoner1Casts(String.valueOf(matchParticipantEntity.getSummoner1Casts()));
        participantDto.setSummoner1Id(String.valueOf(matchParticipantEntity.getSummoner1Id()));
        participantDto.setSummoner2Casts(String.valueOf(matchParticipantEntity.getSummoner2Casts()));
        participantDto.setSummoner2Id(String.valueOf(matchParticipantEntity.getSummoner2Id()));
        participantDto.setSummonerId(matchParticipantEntity.getSummonerId());
        participantDto.setSummonerLevel(String.valueOf(matchParticipantEntity.getSummonerLevel()));
        participantDto.setSummonerName(matchParticipantEntity.getSummonerName());
        participantDto.setTeamEarlySurrendered(String.valueOf(matchParticipantEntity.isTeamEarlySurrendered()));
        participantDto.setTeamId(String.valueOf(matchParticipantEntity.getTeamId()));
        participantDto.setTeamPosition(matchParticipantEntity.getTeamPosition());
        participantDto.setTimeCCingOthers(String.valueOf(matchParticipantEntity.getTimeCCingOthers()));
        participantDto.setTimePlayed(String.valueOf(matchParticipantEntity.getTimePlayed()));
        participantDto.setTotalDamageDealt(String.valueOf(matchParticipantEntity.getTotalDamageDealt()));
        participantDto.setTotalDamageDealtToChampions( String.valueOf(matchParticipantEntity.getTotalDamageDealtToChampions()));
        participantDto.setTotalDamageShieldedOnTeammates(String.valueOf(matchParticipantEntity.getTotalDamageShieldedOnTeammates()));
        participantDto.setTotalDamageTaken(String.valueOf(matchParticipantEntity.getTotalDamageTaken()));
        participantDto.setTotalHeal(String.valueOf(matchParticipantEntity.getTotalHeal()));
        participantDto.setTotalHealsOnTeammates(String.valueOf(matchParticipantEntity.getTotalHealsOnTeammates()));
        participantDto.setTotalMinionsKilled(String.valueOf(matchParticipantEntity.getTotalMinionsKilled()));
        participantDto.setTotalTimeCCDealt(String.valueOf(matchParticipantEntity.getTotalTimeCCDealt()));
        participantDto.setTotalTimeSpentDead(String.valueOf(matchParticipantEntity.getTotalTimeSpentDead()));
        participantDto.setTotalUnitsHealed(String.valueOf(matchParticipantEntity.getTotalUnitsHealed()));
        participantDto.setTripleKills(String.valueOf(matchParticipantEntity.getTripleKills()));
        participantDto.setTrueDamageDealt(String.valueOf(matchParticipantEntity.getTrueDamageDealt()));
        participantDto.setTrueDamageDealtToChampions(String.valueOf(matchParticipantEntity.getTrueDamageDealtToChampions()));
        participantDto.setTrueDamageTaken(String.valueOf(matchParticipantEntity.getTrueDamageTaken()));
        participantDto.setTurretKills(String.valueOf(matchParticipantEntity.getTurretKills()));
        participantDto.setTurretTakedowns(String.valueOf(matchParticipantEntity.getTurretTakedowns()));
        participantDto.setTurretsLost(String.valueOf(matchParticipantEntity.getTurretsLost()));
        participantDto.setUnrealKills(String.valueOf(matchParticipantEntity.getUnrealKills()));
        participantDto.setVisionScore(String.valueOf(matchParticipantEntity.getVisionScore()));
        participantDto.setVisionWardsBoughtInGame(String.valueOf(matchParticipantEntity.getVisionWardsBoughtInGame()));
        participantDto.setWardsKilled(String.valueOf(matchParticipantEntity.getWardsKilled()));
        participantDto.setWardsPlaced(String.valueOf(matchParticipantEntity.getWardsPlaced()));
        participantDto.setWin(String.valueOf(matchParticipantEntity.isWin()));
        participantDto.setRrt(matchParticipantEntity.getRrt());

        return  participantDto;
    }
}